name: CI-CD

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  check-out :
    runs-on: ubuntu-latest
    steps:
      - name: 'check out'
        uses:  actions/checkout@v3
      - name: 'Unit test'
        run:  echo "unit test"
      - name: 'Maven build'
        run: echo "maven build"
  docker-image-build:
    runs-on: ubuntu-latest
    needs: check-out
    steps:
      - name: 'build docker image'
        run: echo "build docker image"
      - name: 'push image to docker hub'
        run: echo "push image to docker hub"
  update-deployment-yaml:
    runs-on: ubuntu-latest
    needs: docker-image-build
    steps:
      - name: 'check out'
        uses: actions/checkout@v3
      - name: 'Update Image Version in the related deployment.yaml'
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'deployment/deployment.yaml'
          propertyPath: 'spec.template.spec.template.metadata.labels.app'
          value: '1.1.0'
          branch: development/infrastructure
          targetBranch: master
          createPR: true
          message: 'update image version to deployment.yaml' 
          token: '${{ secrets.TOKEN }}'
          description: 'update image version'
          title: 'pull reqeust for updating image version'
          workDir: infrastructure
