name: workflow inputs

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
    
jobs:
  apply-slack-notify:
    runs-on: ubuntu-latest
    steps:
      - name: 'check comments'
        uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: 'apply'
        env:
          GITHUB_TOKEN: '${{ secrets.TOKEN }}'
      - name: 'pull request can be applied'
        if: steps.check.outputs.triggered == 'true'
        run: 'echo apply changes!'
      - name: 'pull request can not be applied'
        if: steps.check.outputs.triggered == 'false'
        run: 'echo can not apply'
      - name: 'send pull reqeust notification to slack'
        if: steps.check.outputs.triggered == 'true'
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK:  ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "${{steps.check.outputs.triggered == 'true' ? 'Your changes have been applied !' : 'There are some issues on your changes, please solve it!'}}"
        


    
