name: workflow inputs

on:
  pull_request:
    branches:
      - master
  workflow_call:
    inputs:
      operation:
        description: desc your operation
        default: "apply"
        required: true
        type: string

  
  

jobs:
  inputs-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: print inputs
        run: |
          echo inputs of operation is : ${{ inputs.operation }}


    
