name: workflow inputs

on:
  workflow_dispatch:
    inputs:
      operation:
        description: 'desc your operation'
        required: true
  pull_request:
    branches:
      - master
jobs:
  inputs-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: print inputs
        run: |
          echo inputs of operation is : ${{ github.event.inputs.operation }}


    
