name: Shell Commands

on: [push]

jobs:
  run-first-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello my first github workflow"
      - name: check nodeJS & NPM version
        run: |
          node -v
          npm -v
      - name: Validate YAML
        uses: brittonhayes/validate-yaml@v0.3.0
        with:
          schemaPath: 'event/schema.json'
          files: |
            event/config/*.yaml
