name: YAML validate WF

on: [push]

jobs:
  yaml-validation-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: Validate YAML
        uses: brittonhayes/validate-yaml@v0.3.0
        with:
          schemaPath: 'event/schema.json'
          files: |
            event/config/dev.yaml
            event/config/qa.yaml
            event/config/uat.yaml
            event/config/prod.yaml
            event/config/event-dev.yaml
            event/config/event-qa.yaml
            event/config/event-uat.yaml
            event/config/event-prod.yaml
