name: YAML validate WF

on: [PUSH]

jobs:
  yaml-validation-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Validate YAML
        uses: brittonhayes/validate-yaml@v0.3.0
        with:
          schemaPath: 'event/schema.json'
          files: |
            event/config/*.yaml
